### ISSUE TITLE
Guess MIME type from file extension

### ISSUE THREAD

**Issue by elephantum** [Othoz/gcsfs#15]
Currently all files created in GCS are created with application/octet-stream MIME type, that makes it impossible to upload images for hotlinking from GCS.

It should be relatively easy to add support for `mimetypes.guess_type`, but it will increase usability of the module a lot.

**Comment by birnbaum** [comment]
Completely agree, thanks for the PR!

Sorry for the failing build, something was misconfigured in the pipeline. I will fix it and make a new release containing your changes right now.

**Comment by birnbaum** [comment]
Released [1.0.0](https://pypi.org/project/fs-gcsfs/)

**Comment by elephantum** [comment]
@birnbaum thanks! switching to your version
