### ISSUE TITLE
After applying fix_storage for first time, second time fix_storage hangs

### ISSUE THREAD

**Issue by enderstorm** [Othoz/gcsfs#19]
Hello,
I've run into this issue:
1. I've created a fresh bucket
2. gsutil cp data to the bucket
3. ran GCSFS.fix_storage(), root_path is default ("")
4. GCSFS created directory markers, also created a "/" directory marker for the bucket's root
5. issue -> I want to create a new directory, so I run GCSFS.fix_storage() again, but it is stuck
```
gcsfs.fix_storage()
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (2): www.googleapis.com:443
DEBUG:urllib3.connectionpool:https://www.googleapis.com:443 "GET /storage/v1/b/redacted/o?projection=noAcl&prefix= HTTP/1.1" 200 249836
<nothing happens>
```
6. If I delete "/" directory marker in bucket root, GCSFS.fix_storage() runs correctly and marks the new directory properly

Btw thanks for this lib.

**Comment by birnbaum** [comment]
Hi! Thanks for the bug report.

I am relatively busy right now and would look into it in a couple of weeks as the bug does not seem very urgent and I assume this is not blocking you, right? If yes, feel free to have a look yourself :)

**Comment by enderstorm** [comment]
Hello, thanks for your quick reply.
It's not urgent :)
I will try to fix fix_storage() method myself if time allows.
As workaround for now I delete the "/" directory marker before applying fix_storage method.

**Comment by bgroenks96** [comment]
I have also observed this issue. @enderstorm do you delete only the '/' marker? Or everything in the bucket?

**Comment by enderstorm** [comment]
@bgroenks96 I only get and remove the root marker blob by `blob = gscfs.bucket.get_blob("/") blob.remove()`, then apply `gcsfs.fix_storage()` where `gcsfs is GCSFS() instance`.

**Comment by birnbaum** [comment]
Sorry for the delay! I fixed `GCSFS.fix_storage()` and will release 1.1.0 now :)
