### ISSUE TITLE
Add equivalent of S3Map to gcsfs

### ISSUE THREAD

**Issue by bgroenks96** [Othoz/gcsfs#21]
`s3fs` has a handy class called `S3Map` that wraps the file system in a `MutableMapping`. This is a necessary feature for use with some third party libraries (in my case, `xarray` and `zarr`).

The implementation is pretty simple and can be ported directly from `s3fs`. I have submitted a pull request doing so.

**Comment by birnbaum** [comment]
Cool, thanks a lot for your contribution! Unfortunately, I am very busy right now, I will test and merge your PR and release a new version once I find the time.
