### ISSUE TITLE
Would it make sense to create missing directory-markers in `getinfo`?

### ISSUE THREAD

**Issue by leberknecht** [Othoz/gcsfs#22]
Im wondering: im creating files on the bucket from another application which doesnt create markers, so i have to write some additional code somewhere to handle this. But i think if i would do a small "does the file exists but the markers along the path are missing? if so, create the markers" snippet somewhere on `getinfo` under the block
```python
if check_parent_dir:
            [...]
            if parent_dir != "/" and not self._get_blob(parent_dir_key):
                raise errors.ResourceNotFound(path)
```
would fix this problem. Is there any reason why this is a bad idea?

**Comment by birnbaum** [comment]
I think we could make this work, although I am not sure it's that easy.

First of all, we would definitely need to make this an option in the constructor as we should not randomly create blobs in some user's bucket without their explicit consent if they only perform e.g. a list operation.

Second, we would need to check if this has any major performance implications.

Lastly, I'm not sure about using `getinfo` for this. It's a pretty implicit assumption that it is called every time before we expect a marker to exist, I would need to look into this. Unfortunately, I'll probably not find the time this year but you can feel free to create a PR. We would also need some more tests for this.

**Comment by leberknecht** [comment]
Hm, i just realized that i can simply use `?strict=False` to solve the problem. Guess thats way more unobtrusive :)
