### ISSUE TITLE
Feature request: Passing more arguments to Client object

### ISSUE THREAD

**Issue by dargueta** [Othoz/gcsfs#26]
I'm working on a large codebase using fs-gcsfs and we'd like to test our code without having to: 1) create development versions of buckets and 2) go through thousands of lines of code to find every bucket, change the name during testing, and remember to change every single one back before deployment.

It'd be really great if there were a way to supply the `api_endpoint` argument to the Client object via the URL. I haven't thought too long about this but I was thinking adding `client_options` as an argument and the value would be a JSON object that we'd then pass directly to the `client_options` argument of Client:

```py
fs.open_fs("gs://my-bucket?client_options=%7B%22api_endpoint%22%3A%20%22http%3A//localhost%3A1234%22%7D")
```

You'd then modify the opener and add:

```py
options_string = parse_result.params.get("client_options")
if options_string is not None:
    # You may need to run options_string through urllib.parse.unquote() first
    client_options = json.loads(options_string)
else:
    client_options = None

return GCSFS(..., client_options=client_options)
```

Then in the GCSFS constructor you'd add an optional `client_options` argument and make a small change to how the client is created:

```py
if self.client is None:
    self.client = Client(client_options=client_options)
```

I know JSON is quite ugly but it'll get the job done and is extensible. Another possibility is using dot notation along with [`dpath`](https://pypi.org/project/dpath/) to get something much more readable:

```py
fs.open_fs("gs://my-bucket?client_options.api_endpoint=http%3A//localhost%3A1234")
```

It's a tad bit more work but I think it'll be fine? Google's API client only defines one client option so far and it's a string. If they add another option (say a timeout length) and it's an integer then we'd have to handle that some other way.

**Comment by birnbaum** [comment]
Hey!

First of all, thanks for your ideas. I don't think there is the need to change the API of the `GCSFS` class for this, there is already the possibility to provide any client to it which is very flexible.  But you are right, currently, there is no way to provide a custom client via the URL.

But as you said, it's quite hard to make some query string option truly extensible unless you use some parsing library like https://github.com/Nanonid/rison - but I'd like to avoid another dependency. imho we can just go for `api_endpoint`, there is no clear benefit in replicating the Google API in the filesystem URL. And while we're at it, I'll also add an option for `project`.

I'll get a PR ready
